site_name: Live Nation
nav:
  - Home: index.md
  - Documentation: documentation.md
  - About: about.md
theme:
  name: material
  palette:
    primary: red
markdown_extensions:
  - admonition
